package com.dsw01.practica02.unit;

import com.dsw01.practica02.dto.EmpleadoCreateRequest;
import com.dsw01.practica02.dto.EmpleadoResponse;
import com.dsw01.practica02.model.Empleado;
import com.dsw01.practica02.repository.EmpleadoRepository;
import com.dsw01.practica02.service.EmpleadoService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class EmpleadoServiceCreateTest {

    @Mock
    private EmpleadoRepository empleadoRepository;

    @InjectMocks
    private EmpleadoService empleadoService;

    @Test
    void shouldCreateEmpleadoWithAutogeneratedClave() {
        EmpleadoCreateRequest request = new EmpleadoCreateRequest();
        request.setNombre("Juan");
        request.setDireccion("Av. Principal 123");
        request.setTelefono("555-1234");

        Empleado persisted = new Empleado();
        persisted.setClave(10L);
        persisted.setNombre("Juan");
        persisted.setDireccion("Av. Principal 123");
        persisted.setTelefono("555-1234");

        when(empleadoRepository.save(any(Empleado.class))).thenReturn(persisted);

        EmpleadoResponse response = empleadoService.create(request);

        assertEquals(10L, response.getClave());
        assertEquals("Juan", response.getNombre());
        verify(empleadoRepository).save(any(Empleado.class));
    }
}
